### ISSUE TITLE
Missing create-react-class

### ISSUE THREAD

**Issue by giuliogatto** [AshleyGrant/aurelia-loves-react#1]
Hi 
first of all thank you for your hard work!
I have cloned your repo, but when I run: 
au run --watch
I get the following error:

File not found or not accessible: /Users/giuliogatto/Code/Aurelia/aurelia-react/aurelia-loves-react/src/create-react-class.js. Requested by /Users/giuliogatto/Code/Aurelia/aurelia-react/aurelia-loves-react/src/resources/elements/date-picker.js

 It looks like a dependency is missing so I did:
 npm install 'create-react-class' 
and then added
 import createReactClass from 'create-react-class'; 
to date-picker.js. But I still get the same error... any idea why that's happening, thanks!

**Comment by giuliogatto** [comment]
For anyone finding the same problem the solution is to manually install the missing dependency:
npm install create-react-class --save

And then edit aurelia.json dependencies, adding:
{
            "name": "create-react-class",
            "path": "../node_modules/create-react-class/"
          },

I am going to do a PR asap with the changes

**Comment by AshleyGrant** [comment]
Thanks for the fix. I haven't maintained this repo as it turned out to be so easy to use React components in Aurelia that I didn't see much need for it. I hope it was helpful though.
